#屏蔽文档接口(默认false,生产环境改为true)
knife4j:
  production: false
spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      password: 123456
      url: jdbc:mysql://localhost:3306/blog?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false&allowMultiQueries=true&allowPublicKeyRetrieval=true
      username: root
      initial-size: 20
      max-active: 200
      min-idle: 8
      max-wait: 60000
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    password:
    timeout: 5000ms
    jedis:
      pool:
        min-idle: 0
        max-idle: 8
        max-wait: -1ms
        max-active: 8
  messages:
    encoding: UTF-8
    basename: i18n.message
  servlet:
    multipart:
      enabled: true
      # 文件写入磁盘的阈值
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB
  mvc:
    format:
      date: yyyy-MM-dd HH:mm:ss
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8