version: "3.1"
services:
  mysql:
    image: daocloud.io/library/mysql:8.0.1
    restart: always
    container_name: mysql-8.0.1
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=123456
  redis:
    image: redis:6.2.5
    restart: always
    container_name: redis-6.2.5
    ports:
      - 6379:6379
    # 持久化方式启动
    command: ["redis-server" ,"--appendonly" ,"yes"]
  nacos:
    image: nacos/nacos-server
    container_name: nacos-standalone-mysql
    environment:
      - MODE=standalone
      - SPRING_DATASOURCE_PLATFORM=mysql
      - MYSQL_SERVICE_HOST=mysql地址
      - MYSQL_MASTER_SERVICE_PORT=3306
      - MYSQL_SERVICE_USER=mysql用户名
      - MYSQL_SERVICE_PASSWORD=mysql登录密码
      - MYSQL_SERVICE_DB_NAME=wilton_nacos
      - JVM_XMS=512m
      - JVM_MMS=320m
    volumes:
      - /wilton/nacos/custom/conf:/home/nacos/conf
      - /wilton/nacos/custom/init.d/custom.properties:/home/nacos/init.d/custom.properties
      - /wilton/nacos/custom/logs:/home/nacos/logs
    ports:
      - "8848:8848"
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.1
    restart: always
    container_name: elasticsearch-7.15.1
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
  kibana:
    image: docker.elastic.co/kibana/kibana:7.15.1
    restart: always
    container_name: kibana-7.15.1
    ports:
      - 5601:5601
    environment:
      - elasticsearch_url=http://127.0.0.1:9200
    depends_on:
      - elasticsearch